# Generated by Django 5.1.7 on 2025-04-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_options_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_assigned',
            field=models.BooleanField(default=False, verbose_name='Назначен ли ответственный'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В работе'), ('solved', 'Решен'), ('closed', 'Закрыт'), ('awaiting_response', 'Ожидает ответа'), ('awaiting_action', 'Ожидает действий')], default='awaiting_action', max_length=20, verbose_name='Статус'),
        ),
    ]
