# Generated by Django 5.1.7 on 2025-04-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_is_assigned_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_modified',
            field=models.BooleanField(default=False, verbose_name='Редактировался'),
        ),
    ]
