# Generated by Django 5.1.7 on 2025-04-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment_is_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_overdue',
            field=models.BooleanField(default=False, verbose_name='Просрочено'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_overdue'], name='app_task_is_over_2926b8_idx'),
        ),
    ]
