# Generated by Django 5.1.7 on 2025-05-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_profile_picture_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='../../minio_data/media/attachments/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='../../minio_data/media/profiles/', verbose_name='Фото профиля'),
        ),
    ]
