# Generated by Django 5.1.7 on 2025-05-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_user_middle_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/task_{instance.task.id}', verbose_name='Файл'),
        ),
    ]
