# Generated by Django 5.1.7 on 2025-05-04 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузивший пользователь'),
            preserve_default=False,
        ),
    ]
