# Generated by Django 5.1.7 on 2025-05-04 16:46

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_attachment_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=app.models.get_attachment_upload_path, verbose_name='Файл'),
        ),
    ]
