# Generated by Django 5.1.7 on 2025-05-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_team_task_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
    ]
